XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXX XXXXX X
            XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX XXXXXX
            X

            XXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX XXXXXXX
            X

            XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXX XXXXXXX
            X
        X
    XXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        
XXXXXX
XXXXXXX
XXXXXXX
