version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/DockerFile
    ports:
      - 8000:8000
    volumes:
      - ../db:/db
      - ./:/depository
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/depository.conf:/etc/nginx/conf.d/depository.conf
      - ./public/static:/STATIC
      - ./public/media:/MEDIA
    depends_on:
      - web
