XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXX
        X X XXXXXXX XXXXX X XXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXX
            XXXXXX XXXX
        X X XXXXXXX XXXXX X XXX
        X

        XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXX
        X

        XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
XXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX
