XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXX
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XXX X
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
        X

        XXX X
            XXXXXXXXXXXX XXXX
        X

        XXXXXXXX X
            XXXXXXX XXXXXX
        X

        XXXXXXX X
            XXXXXXXXXXX XXXXX XXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
XXXXX
    
XXXXXX
XXXXX
    
XXXXXX
XXXXX
    
XXXXXX
XXXX XXXXXXXXXXXXXXX
XXXXXX
XXXXX
    
XXXXXX
XXXX XXXXXXXXXXX
    
XXXXXX
XXXXX
    XXXX XXXXXX XXXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXX
    
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX
    
XXXXXX
XXXXX
    XXX XXXXX XXXXX
XXXXXX
XXXXXXX
XXXXXXX
