---
- name: Delete Lock
  file:
    state: absent
    path: "{{ item.path }}"
  with_items:
    - path: "/var/lib/dpkg/lock-frontend"
    - path: "/var/lib/dpkg/lock"
- name: reconfigure
  shell: dpkg --configure -a

- name: Set timezone to Asia/Baghdad
  community.general.timezone:
      name: Asia/Baghdad

- name: Installing Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - git
    - htop
    - iotop
    - vim
    - gettext
    - pkg-config
    - supervisor
    - build-essential
    - libssl-dev
    - libffi-dev
    - supervisor
    - locales-all
    - wkhtmltopdf

-   name: Ensure printer dependencies are installed
    apt:
        pkg: ["libusb-1.0-0", "cups"]
        state: latest
        update_cache: yes

- name: Uploading SSH key
  copy:
    content: '{{ item.contents }}'
    dest: '{{ item.dest }}'
    mode: 0600
  with_items:
    - contents: '{{ ssh_key_public }}'
      dest: ~/.ssh/id_rsa.pub
    - contents: '{{ ssh_key }}'
      dest: ~/.ssh/id_rsa
  become: true
  become_user: '{{ username }}'
