username: "khat"
base_directory: "/home/khat"
venv_directory: "{{ base_directory }}/.venv/depository"
code_directory: "{{ base_directory }}/depository"
resource_directory: "{{ base_directory }}/Desktop/resources"
usb_directory: "/media/USB"
git_repository: "git@github.com:vahidamintabar/depository.git"

ssh_key_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+JXuwIR0eHAtBzr/9mQ+4PUJJfCZSuDsqIAZrx8fu6k0iJLbm8MS4gW4taSeKc5TxQmxUQEWqflcW4RgRRD5D6E4BbhxGdCfJwVe5uvsomgDLxqewFhsULcIHyHMKVxGXwGw+PG+drVktXNM2D/sTIym+r1CWW2u1puIwn0X42miTS049Pi8mnuUdL8mOSuCfPu2Pj6aTAZa4iuNRgW5a9VVzN5rdB5cnmlcPOjsKhV5Ien5uHeT4rHomR1U5ulNA2P13+0z0DnlWZ8uzjJo6TK5yfLrEYtxbFdKoAka3zqxMGYhctS4UDzPEZ/q6GUp4rEnh63t+7JOa0PYE3JQf khat@khat-desktop
ssh_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAviV7sCEdHhwLQc6//ZkPuD1CSXwmUrg7KiAGa8fH7upNIiS2
  5vDEuIFuLWkninOU8UJsVEBFqn5XFuEYEUQ+Q+hOAW4cRnQnycFXubr7KJoAy8an
  sBYbFC3CB8hzClcRl8BsPjxvna1ZLVzTNg/7EyMpvq9QlltrtabiMJ9F+Npok0tO
  PT4vJp7lHS/Jjkrgnz7tj4+mkwGWuIrjUYFuWvVVczea3QeXJ5pXDzo7CoVeSHp+
  bh3k+Kx6JkdVObpTQNj9d/tM9A55VmfLs4yaOkyucny6xGLcWxXSqAJGt86sTBmI
  XLUuFA8zxGf6uhlKeKxJ4et7fuyTmtD2BNyUHwIDAQABAoIBAQCOH4Qw5L9X1wxO
  9tMoITTPt/II7SPT5mJKnT9PZjc5i6V1pM2VFldjtVJ93MAySywDnGtOGfA4fFBq
  CHstxL1pkoRjq0K1InLu6XXBnFHISjvYFDcYdZ1t2rnRiXD7RJMgwzHk3tVqnLww
  HNa97Pn0lu7H2VA54kFCuGcOgq4RTxzRgaLq5kApYuQeG4q41mlUHzZtgfJlITpT
  wNkYxc5N6L6dy3mR1ChOxx7r6U+iccNYd49QNWlPOo+59rF+jWgSi41lTB8wYzAD
  ntd5IpvXxKF4xG3hB7yoCeK3S42hsHIhjl2u67q0a8TXWnX+FHqZwavlPas/S0WI
  JSF8txE5AoGBAN4E+QCa9w/hmeTuF9dfsUXckAZH64R/aG3dmAoZEggk+2+pdE5Q
  DGjD5F2KfkfUb5zeAJWracjpATAnnA4hmakbIdKknXCWKCDHnzjVkDR4lTZPKzym
  xvOCLVaHW5BCQFbKLQyteexQUC/mI4KClgIr3sQNiSEo6T0LkfV8OtWtAoGBANs/
  rqFfu689ZPb7FysQ55kLJTVyq7olGOIBWVk9oAsVwyV3GJuZVPRKmOSf2eSG+Onx
  a2hwu9jESI7YhYmoXOsOPJRHSf/Gr6ceCV3D1DQovcf5j/jufMTYj3WwJH6gq7tR
  JA5ebxiv0QyJpSEpvVc5eFg00XpXO7UnoqpgkNJ7AoGBAJeaT6lxJ8lpZJulVRRV
  HIi23oXbcGAOW/HBgcNLcTusfSC3VlrvYDndob+aBTbpQbmdAksxPE/bg1stgOtJ
  WFLX2xWqIHOzpP0VMo0tj4W03TazgrOssmeu+WR/ky+DfcmFzpM8leeew9KhVJgW
  sXYUHM5E6+F/vRxZHTbCuK4VAoGAFvMXiHTI5JL8mo214yAl3fM4tduG9jkj3aRe
  geTdd8uTXbyVqtPl/JxCXMwOtskaDQLkR05lm08QeUNY1wv0jfYziSHdMRTPFiMi
  v9nbwInzM5d/5oKwNLqmaZ9Ccq7Gyxi3OXnRDzh4HWPbERmZZCPz4OfGdZPkABZi
  BIuPHTkCgYB604G8u+r3fnkn3LPHnXLtCK/Zoi3801W2JO3jEd4JtEd5vX765xhz
  30L4d1haAiD3NQHJl0qyRE+Bv9IESxIBbcvkFujX1E4TgpslfyKdezcHBTf3awk4
  zyTE1DveJB3ElhBLl8NoCXpHn1Kd6sfQy48PW6+ttvaskUYXGcxmSA==
  -----END RSA PRIVATE KEY-----
