FROM python:3.6
EXPOSE 8000
ADD depository/requirements.txt /
RUN pip install -r requirements.txt

WORKDIR /depository
RUN sudo apt-get install wkhtmltopdf -y && mkdir temp && mkdir temp/pdf && mkdir temp/barcode
#RUN python manage.py migrate
#RUN python manage.py collectstatic --noinput
CMD gunicorn depository.wsgi --log-level info --bind 0.0.0.0:8000



