# Generated by Django 3.0.5 on 2020-05-20 01:36

import depository.apps.reception.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=depository.apps.reception.models.hash_id_generator, max_length=32)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('exit_type', models.IntegerField(blank=True, choices=[(0, 'تحویل به زائر'), (1, 'انتقال به انبار'), (2, 'گم شده')], null=True)),
                ('depository', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.Depository')),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='givers', to=settings.AUTH_USER_MODEL)),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Pilgrim')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField(default=0)),
                ('suitcase_count', models.IntegerField(default=0)),
                ('pram_count', models.IntegerField(default=0)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Cell')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='reception.Delivery')),
            ],
        ),
    ]
