# Generated by Django 2.2.4 on 2019-08-01 10:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import depository.apps.reception.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=depository.apps.reception.models.hash_id_generator, max_length=4)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('exit_type',
                 models.IntegerField(blank=True, choices=[(0, 'delivered to customer'), (1, 'delivered to store')],
                                     null=True)),
                ('depository',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.Depository')),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='givers', to=settings.AUTH_USER_MODEL)),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Pilgrim')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takers',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField(default=0)),
                ('suitcase_count', models.IntegerField(default=0)),
                ('pram_count', models.IntegerField(default=0)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Cell')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs',
                                               to='reception.Delivery')),
            ],
        ),
    ]
