# Generated by Django 2.2.2 on 2019-09-09 11:00

import depository.apps.reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20190820_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='hash_id',
            field=models.CharField(default=depository.apps.reception.models.hash_id_generator, max_length=32),
        ),
    ]
