---
# - name: Add a Python 3.7 PPA
#   apt_repository:
#     repo: "ppa:jonathonf/python-3.7"
#     state: present

- name: Installing Python
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python3.7
    - python3.7-venv
    - python3.7-dev
    - python3-pip


- name: Install Virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
    state: latest