---
- name: Add a Python 3.6 PPA
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present

- name: "installing python"
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python3.6
    - python3.6-venv
    - python3.6-dev
    - python3-pip


- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
    state: latest