---
- name: Add a Python 3.6 PPA
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present
  become_user: "{{ username }}"
  become: yes

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
    state: latest