# Generated by Django 2.2.4 on 2019-08-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Depository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('is_healthy', models.BooleanField(default=True)),
                ('size', models.IntegerField(choices=[(0, 'Small'), (1, 'Large')], default=0)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Row')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='depository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Depository'),
        ),
    ]
