# Generated by Django 2.2.4 on 2019-08-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='is_asc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='order',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cell',
            name='code',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells',
                                    to='structure.Row'),
        ),
        migrations.AlterField(
            model_name='row',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows',
                                    to='structure.Cabinet'),
        ),
        migrations.AlterField(
            model_name='row',
            name='code',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
