# Generated by Django 2.2.2 on 2019-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20190808_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
