# Generated by Django 2.2.4 on 2019-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_depository_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='is_asc',
            field=models.NullBooleanField(default=True),
        ),
    ]
