# Generated by Django 2.2.4 on 2019-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_auto_20190830_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='constant',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
