# Generated by Django 2.2.4 on 2019-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20190911_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='size',
            field=models.IntegerField(choices=[(0, 'کوچک'), (1, 'بزرگ')], default=0),
        ),
        migrations.AlterField(
            model_name='depository',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
