# Generated by Django 3.0.5 on 2020-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20191005_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='code',
            field=models.CharField(max_length=1),
        ),
    ]
