# Generated by Django 3.0.5 on 2020-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20200423_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='code',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
