# Generated by Django 3.0.5 on 2020-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_auto_20200425_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
