# Generated by Django 3.0.5 on 2020-05-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_auto_20200429_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='depository',
            name='code',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depository',
            name='printer_id',
            field=models.IntegerField(blank=True, default=14),
            preserve_default=False,
        ),
    ]
