---
- name: Disable apache2
  ansible.builtin.service:
    name: apache2
    enabled: no
    state: stopped
  ignore_errors: yes

- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: Clean directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - path: "/etc/nginx/sites-enabled/default"
    - path: "/etc/nginx/sites-enabled/default.conf"

- name: "nginx configuration"
  template: src=depository.conf
            dest=/etc/nginx/sites-enabled/default.conf
            mode=0644
  notify: restart nginx
