---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: Clean directory
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/*"

- name: "nginx configuration"
  template: src=depository.conf
            dest=/etc/nginx/sites-enabled/default.conf
            mode=0644
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
