# Generated by Django 2.2.4 on 2019-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
