# Generated by Django 2.2.4 on 2019-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_pilgrim_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
