---
- name: Ensure printer dependencies are installed
  apt:
    pkg: ["libusb-1.0-0", "cups"]
    state: latest
    update_cache: yes


# TODO: replace `khat` with a variable
- name: Add user to lpadmin group
  command: usermod -a -G lpadmin khat
  become: yes
  become_user: root


- name: Copy printer driver installer
  copy:
    src: ../Oscar
    dest: /home/khat/Desktop/resources


- name: Change uninstall.sh permitions
  command: chmod +x "/home/khat/Desktop/resources/Oscar/printer/cupsprintdrv-1.1.0_linux/install/uninstall.sh"
  become: yes
  become_user: root


- name: Change install.sh permitions
  command: chmod +x "/home/khat/Desktop/resources/Oscar/printer/cupsprintdrv-1.1.0_linux/install/install.sh"
  become: yes
  become_user: root


- name: Uninstall Oscar driver
  command: chdir=/home/khat/Desktop/resources/Oscar/printer/cupsprintdrv-1.1.0_linux/install/ ./uninstall.sh
  become: yes
  become_user: root


- name: Install Oscar driver
  command: chdir=/home/khat/Desktop/resources/Oscar/printer/cupsprintdrv-1.1.0_linux/install/ ./install.sh
  become: yes
  become_user: root


- name: Add printer to CUPS
  command: lpadmin -p "OSCAR-POS88F-NET" -E -v socket://192.168.0.114:9100 -P /usr/share/cups/model/printer/80mmSeries.ppd.gz -D "Decs" -L "Loc"
# For more information about cups commads read following links:
# https://www.techrepublic.com/article/control-printers-in-linux-from-the-command-line/
# https://www.thegeekstuff.com/2015/01/lpadmin-examples/
